set positional-arguments := true
set shell := ["bash", "-euo", "pipefail"]

set fallback := true

[private]
_help:
    @just --list --list-submodules

# build:
#     "${VIRTUAL_ENV}/bin/python" -m west \
#         build \
#         -p always \
#         -b esp32s3_devkitc/esp32s3/procpu \
#         -- \
#         -DDTC_OVERLAY_FILE=boards/esp32s3_devkitc.overlay

# flash port="/dev/cu.usbmodem101":
#     "${VIRTUAL_ENV}/bin/python" -m esptool \
#         --port "{{port}}" \
#         --chip auto \
#         --baud 921600 \
#         --before default_reset \
#         --after hard_reset write_flash \
#         -u --flash_mode keep \
#         --flash_freq 40m \
#         --flash_size detect 0x0 \
#         ./build/zephyr/zephyr.bin

# flash-from-host port="/dev/cu.usbmodem101":
#     uvx esptool \
#         --port "{{port}}" \
#         --chip auto \
#         --baud 921600 \
#         --before default_reset \
#         --after hard-reset write-flash \
#         -u --flash-mode keep \
#         --flash-freq 40m \
#         --flash-size detect 0x0 \
#         ./build/zephyr/zephyr.bin

# show-ports:
#     uvx --from pyserial pyserial-ports  

# serial-from-host port="/dev/cu.usbmodem101" baud="115200":
#     # python3 -m serial.tools.miniterm "{{port}}" 115200
#     uvx --from pyserial pyserial-miniterm - "{{baud}}"
#     # python -m esptool --port " " --chip auto --baud 921600 --before default_reset --after hard_reset write_flash -u --flash_size detect 0x0 workspace/apps/01_blink/build/zephyr/zephyr.bin